webtalk_init -webtalk_dir /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 14 15:00:25 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1fueljvq65rtfq0i5vd8k82k03" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1481723999000" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1481723999000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1481723999000"
webtalk_transmit -clientid 436725636 -regid "" -xml /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
