# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/torbjorn/development/vhdl/cifra/zync_demo_anti/arty_z7_20_foc.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_1/zsys_processing_system7_0_1.xci
# IP: The module: 'zsys_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/torbjorn/development/vhdl/cifra/zync_demo_anti/arty_z7_20_foc.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_1/zsys_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/torbjorn/development/vhdl/cifra/zync_demo_anti/arty_z7_20_foc.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_1/zsys_processing_system7_0_1.xci
# IP: The module: 'zsys_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/torbjorn/development/vhdl/cifra/zync_demo_anti/arty_z7_20_foc.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_1/zsys_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
