# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/vivado_target.xdc

# XDC: imports/constraints/Arty_Z7.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_1/zsys_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_1 || ORIG_REF_NAME==zsys_processing_system7_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_emio_sdemu_0_0/zsys_emio_sdemu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_emio_sdemu_0_0 || ORIG_REF_NAME==zsys_emio_sdemu_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys_reset_0_0 || ORIG_REF_NAME==zsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_wb2axi_0_0/zsys_wb2axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_wb2axi_0_0 || ORIG_REF_NAME==zsys_wb2axi_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_protocol_converter_0_0/zsys_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_protocol_converter_0_0 || ORIG_REF_NAME==zsys_axi_protocol_converter_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_sdio_monitor_axis_v1_0_0_0/zsys_sdio_monitor_axis_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_sdio_monitor_axis_v1_0_0_0 || ORIG_REF_NAME==zsys_sdio_monitor_axis_v1_0_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_system_ila_0_0/zsys_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_system_ila_0_0 || ORIG_REF_NAME==zsys_system_ila_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_data_fifo_0_0 || ORIG_REF_NAME==zsys_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_clock_detector_0_0/zsys_clock_detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_clock_detector_0_0 || ORIG_REF_NAME==zsys_clock_detector_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_interconnect_0_0/zsys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_interconnect_0_0 || ORIG_REF_NAME==zsys_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_bram_ctrl_0_0/zsys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zsys_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_bram_ctrl_0_bram_0/zsys_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==zsys_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_vio_0_0/zsys_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_vio_0_0 || ORIG_REF_NAME==zsys_vio_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_bram_ctrl_1_0/zsys_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_bram_ctrl_1_0 || ORIG_REF_NAME==zsys_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_interconnect_1_0/zsys_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_interconnect_1_0 || ORIG_REF_NAME==zsys_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_0 || ORIG_REF_NAME==zsys_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_0 || ORIG_REF_NAME==zsys_auto_pc_0} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
