# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.cache/wt [current_project]
set_property parent.project_path /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0725_100_2c:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/torbjorn/development/vhdl/cifra/ip_repo/chacha_stream_and_address_1.0
  /home/torbjorn/development/vhdl/cifra/ip_repo/chacha_stream_and_address_1.0
  /home/torbjorn/development/vhdl/cifra/ip_repo/chacha_stream_and_address_1.0
  /home/torbjorn/development/vhdl/cifra/ip_repo/chacha_axi_ip_1.0
  /home/torbjorn/development/vhdl/cifra/ip_repo/myip_1.0
  /home/torbjorn/development/vhdl/cifra/ip_repo/My_stream_test_1.0
  /home/torbjorn/development/vhdl/cifra/antis_chacha
} [current_project]
add_files /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/design_2_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/design_2_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axis_dwidth_converter_0_0/design_2_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/ip/design_2_axis_dwidth_converter_1_0/design_2_axis_dwidth_converter_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/design_2_ooc.xdc]
set_property is_locked true [get_files /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/design_2.bd]

read_vhdl -library xil_defaultlib /home/torbjorn/development/vhdl/cifra/chacha_ip_test/chacha_ip_test.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_2_wrapper -part xc7a100tcsg324-2


write_checkpoint -force -noxdef design_2_wrapper.dcp

catch { report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb }
