# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2}]

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0}]

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0}]

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0}]

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0}]

# IP: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_0 || ORIG_REF_NAME==design_2_microblaze_0_0}]

# IP: bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_0 || ORIG_REF_NAME==design_2_dlmb_v10_0}]

# IP: bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_0 || ORIG_REF_NAME==design_2_ilmb_v10_0}]

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/design_2_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_0}]

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/design_2_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_0}]

# IP: bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_0 || ORIG_REF_NAME==design_2_lmb_bram_0}]

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_0/design_2_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_0}]

# IP: bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_intc_0}]

# IP: bd/design_2/ip/design_2_microblaze_0_xlconcat_0/design_2_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_2_microblaze_0_xlconcat_0}]

# IP: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0}]

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0}]

# IP: bd/design_2/ip/design_2_chacha_axi_ip_0_0/design_2_chacha_axi_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_chacha_axi_ip_0_0 || ORIG_REF_NAME==design_2_chacha_axi_ip_0_0}]

# IP: bd/design_2/ip/design_2_axis_dwidth_converter_0_0/design_2_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axis_dwidth_converter_0_0 || ORIG_REF_NAME==design_2_axis_dwidth_converter_0_0}]

# IP: bd/design_2/ip/design_2_axis_dwidth_converter_1_0/design_2_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axis_dwidth_converter_1_0 || ORIG_REF_NAME==design_2_axis_dwidth_converter_1_0}]

# IP: bd/design_2/ip/design_2_util_vector_logic_0_0/design_2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_0 || ORIG_REF_NAME==design_2_util_vector_logic_0_0}]

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_0 || ORIG_REF_NAME==design_2_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_0 || ORIG_REF_NAME==design_2_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_0 || ORIG_REF_NAME==design_2_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/design_2_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/design_2_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0_ooc_trace.xdc

# XDC: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axis_dwidth_converter_0_0/design_2_axis_dwidth_converter_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axis_dwidth_converter_1_0/design_2_axis_dwidth_converter_1_0_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
